version: '2'
services:
    symfony:
        extends:
            file: docker-compose-dev.yml
            service: parent
        build: docker/symfony
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql

    nginx:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - symfony

    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - data:/var/lib/mysql

volumes:
    data:
